// generated by Fast Light User Interface Designer (fluid) version 1.0307

#ifndef ui_h
#define ui_h
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Progress.H>
#include <FL/Fl_Text_Display.H>

class user_interface {
public:
  user_interface();
  Fl_Input *input_path_;
  Fl_Button *btn_sel_path_;
  Fl_Check_Button *check_skip_;
  Fl_Check_Button *check_delete_;
  Fl_Button *btn_stop_;
  Fl_Button *btn_go_;
  Fl_Progress *progress_;
  Fl_Text_Display *text_disp_log_;
};
#endif
